name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build the Docker image
        run: docker build -t your-dockerhub-username/book-management-system:latest .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push your-dockerhub-username/book-management-system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Only run after build-and-push
    steps:
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull your-dockerhub-username/book-management-system:latest
            docker-compose down # Or docker stop/rm, depending on your setup
            docker-compose up -d  # Or docker run
